### ISSUE TITLE
Maybe you can get som insperation with this links:

### ISSUE THREAD

**Issue by norbertfuhs** [Talento90/gotasky#1]
[webapp-with-golang-the-antitextbook](https://www.gitbook.com/book/thewhitetulip/webapp-with-golang-anti-textbook/details)
[Effective Go](https://golang.org/doc/effective_go.html)
[GoBridge Slack](https://invite.slack.golangbridge.org/)
[GoBridge Forum](https://forum.golangbridge.org/)

**Comment by Talento90** [comment]
@norbertfuhs Thanks for the links 👍

Do you recommend any Book?

**Comment by norbertfuhs** [comment]
[Go in Action](http://goinactionbook.com/)
And the free book [webapp-with-golang-anti-textbook](https://www.gitbook.com/book/thewhitetulip/webapp-with-golang-anti-textbook/details)
Here is  a more detailed list [GoBooks](https://github.com/dariubs/GoBooks)

**Comment by norbertfuhs** [comment]
Heres a more detailed document by Todd McLeod [Resources]( https://goo.gl/W1hfbf )
Now I think you have a good overview about go based books.
Best regards Norbert
